[theme]
name = "rose-pine"

[colors]
# AlertInfo: alerting the user at an INFO level
AlertInfo = "#3e8fb0"
# AlertWarn: alerting the user at a WARN level
AlertWarn = "#eb6f92"
# AlertError: alerting the user at an ERROR level
AlertError = "#f6c177"
# Annotation: less-critical, supporting text
Annotation = "#e0def4"
# Base: default foreground color
Base = "#e0def4"
# Guidance: instructing the user as help or context
Guidance = "#ea9a97"
# Important: drawing the userâ€™s attention to information
Important = "#c4a7e7"
# Title: titling a section or view
Title = "#ebbcba"
