sync_address = "https://atuin.elurz.de"
inline_height = 13 # should show 9 items
style = "compact"
enter_accept = true
keymap_mode = "vim-insert"
# keymap_mode = "vim-normal"
secrets_filter = true
# any command that starts with whitespace will not be saved to history
history_filter = [ "^\\s+.*" ]
