k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: finion-dev
  currentCluster: arn:aws:eks:eu-central-1:119920258390:cluster/finion-dev-cluster
  clusters:
    arn:aws:eks:eu-central-1:119920258390:cluster/finion-dev-cluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - load-balancer
        - default
        - monitoring
        - fi-dev
        - fi-testing
        - all
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-central-1:124256140892:cluster/finion-eks-v2-cluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - load-balancer
        - all
        - monitoring
        - default
        - fi-prod
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/4p/r2tgxjz950x175s_8pyzskch0000gn/T/k9s-screens-el
